name: pre-commit

on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  go-mod:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.4
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Check go mod
        run: |
          go mod tidy
          git diff --exit-code go.mod
#  pre-commit:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - uses: actions/setup-python@v2
#      - uses: golangci/golangci-lint-action@v2.5.2
#      - uses: pre-commit/action@v2.0.3